name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

        
      - name: Prepare artifact in staging
        run: mkdir staging && cp target/*.jar staging
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging

  sonar-cloud:
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: ${{secrets.SONAR_URL}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      SONAR_PROJECT_KEY: ${{vars.SONAR_PROJECT_KEY}}
      SONAR_ORGANIZATION: ${{vars.SONAR_ORGANIZATION}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}}
            -Dsonar.host.url=${{env.SONAR_HOST_URL}}
            -Dsonar.login=${{env.SONAR_TOKEN}}
            -Dsonar.working.directory=./.scannerwork     
            -Dsonar.organization=${{env.SONAR_ORGANIZATION}}

          

