name: Terraform Deploy (infra with k8s)

on:
  workflow_dispatch:
    inputs:
      apply-changes:
        description: "Apply changes"
        type: boolean
        default: false

jobs:
  deploy-infra:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform/tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tfplan
        working-directory: ./terraform
        if: ${{ inputs.apply-changes }}

      - name: Get Terraform Outputs
        run: terraform output -json > outputs.json
        working-directory: ./terraform

      - name: Upload Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: ./terraform/outputs.json

      - name: Success Notification
        if: success()
        working-directory: ./terraform
        run: |
          echo "Terraform deployment success!"
          echo "ssh: $(terraform output -raw ssh_connection_command)"
          echo "log execution of user-data: /var/log/user-data.log"
