name: Terraform Destroy Infra

on:
  workflow_dispatch:
    inputs:
      apply-changes:
        description: "Apply destroy"
        type: boolean
        default: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -var="runner_token=${{ secrets.RUNNER_TOKEN }}" -auto-approve
        if: ${{ inputs.apply-changes }}
        working-directory: ./terraform

